/**
 * RecentPages - Shows a short "what's new" list on the homepage
 *
 * `items` is generated by tools/ci/sync-recent-pages.py from this page's own
 * `recent_pages` frontmatter (see .github/workflows/recent-pages-sync.yml) --
 * pinned entries always show, non-pinned entries drop off after 60 days,
 * capped at 7 total. Passed as a literal prop rather than fetched at
 * runtime: Mintlify's custom-component sandbox has no JSON-import support
 * and its static file server doesn't serve arbitrary .json files (confirmed
 * via `mint dev` -- a plain 404), so the resolved list is baked directly
 * into this call at generation time instead of fetched after mount.
 *
 * @param {Object} props
 * @param {Array<{path: string, title: string, since: string, pinned?: boolean}>} props.items
 *
 * @example
 * import RecentPages from "/components/recent-pages.jsx";
 *
 * <RecentPages items={[
 *   { path: "/release-notes/12", title: "What's new in SuperOffice 12", since: "08.25.2026", pinned: true },
 *   { path: "/en/marketing", title: "Marketing", since: "08.24.2026" }
 * ]} />
 */
const RecentPages = ({ items }) => {
  if (!items || items.length === 0) {
    return null;
  }

  return (
    <div className="recent-pages-list">
      {items.map((item) => (
        <a key={item.path} href={item.path} className="recent-pages-item">
          <span className="recent-pages-title">{item.title}</span>
          <span className="recent-pages-since">{item.since}</span>
        </a>
      ))}
    </div>
  );
};

export default RecentPages;
