#!/usr/bin/env python3
"""Add a `sidebarTitle` to database-reference enum pages (see issue #260).

`en/database/tables/enums/` is wholly generated by an external ADO pipeline
(see #192) - there is no source file in this repo to fix at the root, and
every regen re-pushes the tree wholesale. Every page's `title` follows one
fixed shape, `Enum values for <Name>`, which renders verbatim and far too
long in the sidebar. This script derives a short `sidebarTitle` from that
title and inserts it directly after the `title:` line.

Rule (deliberately narrow - single responsibility, no guessing): only
`Enum values for <Name>` titles are touched. Strip the literal prefix and
use `<Name>` as-is. Any file whose title doesn't match that exact shape is
left untouched and reported separately, since inventing a fallback for an
unknown shape risks a wrong or misleading label reappearing on every future
regen unnoticed.

Scans both `.md` and `.mdx` (fixed 2026-08-19, #266): this tree moved to
`.mdx` the day after this fix originally landed (#232, one day after
#272), and the workflow's `git ls-files -- '*.md'` filter meant it had
been silently inert against every `.mdx` regen since - confirmed live
that `sidebarTitle` was in fact missing again on the `.mdx` files.

Frontmatter is isolated the same way as tools/migration/rename-version-property.py
(and reformat-keywords.py before it): match `^(---\\n)(.*?\\n)(---\\n?)(.*)$`
(DOTALL, non-greedy) against the file with CRLF normalized to LF first, and
only ever edit group 2. BOM is preserved on write if present on read (none
of the 157 files in this tree carry one today, confirmed via `git cat-file`,
but the round-trip is kept for safety against a future regen that does).

Modes:
  Default (no --apply): audit only, reports what would change, no writes.
  --apply: performs the writes for the scoped files.
  Positional file args scope to an explicit list (e.g. a PR's changed-files
  list); --path scopes to a folder instead (default: en/database/tables/enums).

Usage:
    python tools/ci/add-database-enum-sidebar-titles.py                        # audit, default tree
    python tools/ci/add-database-enum-sidebar-titles.py --apply                 # apply, default tree
    python tools/ci/add-database-enum-sidebar-titles.py <file> [<file> ...] --apply
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_PATH = "en/database/tables/enums"

FM_RE = re.compile(r"^(---\n)(.*?\n)(---\n?)(.*)$", re.DOTALL)
TITLE_LINE_RE = re.compile(r"(?m)^title:\s*(.*)$")
SIDEBAR_TITLE_RE = re.compile(r"(?m)^sidebarTitle:")
ENUM_TITLE_RE = re.compile(r"^Enum values for (.+)$")


def list_path_files(scope):
    out = subprocess.run(
        ["git", "ls-files", "--", "*.md", "*.mdx"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    scope_norm = scope.strip("/\\").replace("\\", "/")
    return [f for f in out.stdout.splitlines() if f == scope_norm or f.startswith(scope_norm + "/")]


def process_file(rel_path, apply_changes):
    """Returns a dict describing the outcome, or None if out of scope."""
    path = REPO_ROOT / rel_path
    if not path.is_file() or path.suffix not in (".md", ".mdx"):
        return None

    raw = path.read_bytes()
    has_bom = raw[:3] == b"\xef\xbb\xbf"
    text = raw.decode("utf-8-sig")
    uses_crlf = "\r\n" in text
    if uses_crlf:
        text = text.replace("\r\n", "\n")

    m = FM_RE.match(text)
    if not m:
        return {"path": rel_path, "status": "no-frontmatter"}

    open_marker, fm, close_marker, rest = m.groups()

    if SIDEBAR_TITLE_RE.search(fm):
        return {"path": rel_path, "status": "already-has-sidebar-title"}

    title_match = TITLE_LINE_RE.search(fm)
    if not title_match:
        return {"path": rel_path, "status": "no-title"}

    enum_match = ENUM_TITLE_RE.match(title_match.group(1).strip())
    if not enum_match:
        return {"path": rel_path, "status": "title-does-not-match-pattern", "title": title_match.group(1).strip()}

    name = enum_match.group(1)
    new_line = title_match.group(0) + f'\nsidebarTitle: "{name}"'
    new_fm = fm[: title_match.start()] + new_line + fm[title_match.end() :]

    if apply_changes:
        new_text = open_marker + new_fm + close_marker + rest
        if uses_crlf:
            new_text = new_text.replace("\n", "\r\n")
        encoding = "utf-8-sig" if has_bom else "utf-8"
        path.write_bytes(new_text.encode(encoding))

    return {"path": rel_path, "status": "added", "sidebar_title": name}


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("files", nargs="*", help="Specific files to check (e.g. a PR's changed-files list)")
    parser.add_argument("--path", default=DEFAULT_PATH, help=f"Scope to one folder instead of an explicit file list (default: {DEFAULT_PATH})")
    parser.add_argument("--apply", action="store_true", help="Write the sidebarTitle (default: audit only, no writes)")
    args = parser.parse_args()

    candidates = args.files if args.files else list_path_files(args.path)

    results = {"added": [], "already-has-sidebar-title": [], "title-does-not-match-pattern": [], "no-frontmatter": [], "no-title": []}
    for rel_path in candidates:
        result = process_file(rel_path, args.apply)
        if result is None:
            continue
        results[result["status"]].append(result)

    mode = "Added" if args.apply else "Would add (audit only)"
    print(f"{mode} sidebarTitle on {len(results['added'])} file(s).")
    for r in results["added"]:
        print(f"  {r['path']}: sidebarTitle: \"{r['sidebar_title']}\"")

    if results["title-does-not-match-pattern"]:
        print(f"\nSkipped {len(results['title-does-not-match-pattern'])} file(s) - title doesn't match 'Enum values for <Name>':")
        for r in results["title-does-not-match-pattern"]:
            print(f"  {r['path']}: title: {r['title']}")

    if results["already-has-sidebar-title"]:
        print(f"\n{len(results['already-has-sidebar-title'])} file(s) already have a sidebarTitle (no-op).")

    return 0


if __name__ == "__main__":
    sys.exit(main())
