#!/usr/bin/env python3
"""Fix `title` casing and add a short `sidebarTitle` on MDO-provider pages
with long generated names (see issue #261).

`en/api/mdo-providers/reference/` is wholly generated by an external ADO
pipeline (see #192) - there is no source file in this repo to fix at the
root, and every regen re-pushes the tree wholesale. Most page titles are
short, but 36 of 421 (at the time of writing) share one structured shape:
`relationssearchlistprovider<entity><entity?><active|passive>`, where
<entity> is one of a closed set of 5 (appointment, contact, document,
person, sale) - e.g. `relationssearchlistproviderappointmentappointmentpassive`.
Unrecased and unbroken, that string reads poorly as a page title and
renders far too wide in the sidebar - two separate problems, fixed here in
two separate fields (per direct instruction: preserve every word in
`title`, only `sidebarTitle` may drop the shared prefix):

  title:        relationssearchlistproviderappointmentappointmentpassive
  ->            RelationsSearchListProviderAppointmentAppointmentPassive
  sidebarTitle: "Appointment Appointment Passive"

Rule (deliberately narrow - single responsibility, no guessing, confirmed
with the issue's own reporter before writing this): only titles starting
with the literal `relationssearchlistprovider` prefix (case-insensitively,
so this is idempotent once `title` has already been recased) are touched.
The remainder must fully match <entity><entity?><active|passive> against
the closed 5-entity vocabulary; segments are title-cased. Anything that
doesn't fully match - including the 6 known irregular one-off long names
(`ticketselectionwithstaticmenu`, `importduplicateactionwithoutadd`,
etc.) that don't share this prefix at all - is explicitly out of scope:
left untouched and reported separately, never guessed at.
`en/api/archive-providers/reference/` is a separate, similarly ADO-dropped
tree but was not reported as having this problem and is out of scope
here too (see the issue's own note) - a deliberate choice not to expand
scope unasked, not an oversight.

`title` and `sidebarTitle` are fixed independently and idempotently: a
file that already has the correct `title` but not yet `sidebarTitle` (or
vice versa) only gets the missing piece written.

Frontmatter is isolated the same way as tools/migration/rename-version-property.py:
match `^(---\\n)(.*?\\n)(---\\n?)(.*)$` (DOTALL, non-greedy) against the file
with CRLF normalized to LF first, and only ever edit group 2. BOM is
preserved on write if present on read (none of the 421 files in this tree
carry one today, confirmed via `git cat-file`, but the round-trip is kept
for safety against a future regen that does).

Modes:
  Default (no --apply): audit only, reports what would change, no writes.
  --apply: performs the writes for the scoped files.
  Positional file args scope to an explicit list (e.g. a PR's changed-files
  list); --path scopes to a folder instead (default:
  en/api/mdo-providers/reference).

Usage:
    python tools/ci/add-mdo-provider-sidebar-titles.py                        # audit, default tree
    python tools/ci/add-mdo-provider-sidebar-titles.py --apply                 # apply, default tree
    python tools/ci/add-mdo-provider-sidebar-titles.py <file> [<file> ...] --apply
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_PATH = "en/api/mdo-providers/reference"

FM_RE = re.compile(r"^(---\n)(.*?\n)(---\n?)(.*)$", re.DOTALL)
TITLE_LINE_RE = re.compile(r"(?m)^title:\s*(.*)$")
SIDEBAR_TITLE_RE = re.compile(r"(?m)^sidebarTitle:")

PREFIX = "relationssearchlistprovider"
PREFIX_PASCAL = "RelationsSearchListProvider"
ENTITIES = ("appointment", "contact", "document", "person", "sale")
SUFFIXES = ("active", "passive")
SEGMENT_RE = re.compile(
    r"^(" + "|".join(ENTITIES) + r")(" + "|".join(ENTITIES) + r")?(" + "|".join(SUFFIXES) + r")$"
)


def list_path_files(scope):
    out = subprocess.run(
        ["git", "ls-files", "--", "*.md"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    scope_norm = scope.strip("/\\").replace("\\", "/")
    return [f for f in out.stdout.splitlines() if f == scope_norm or f.startswith(scope_norm + "/")]


def derive_names(title):
    """Returns (desired_title, desired_sidebar_title), or (None, None) if
    `title` (matched case-insensitively) isn't in scope."""
    remainder_match = re.match(r"^" + PREFIX + r"(.*)$", title, re.IGNORECASE)
    if not remainder_match:
        return None, None
    segment_match = SEGMENT_RE.match(remainder_match.group(1).lower())
    if not segment_match:
        return None, None
    segments = [seg.capitalize() for seg in segment_match.groups() if seg]
    return PREFIX_PASCAL + "".join(segments), " ".join(segments)


def process_file(rel_path, apply_changes):
    """Returns a dict describing the outcome, or None if out of scope."""
    path = REPO_ROOT / rel_path
    if not path.is_file() or path.suffix != ".md":
        return None

    raw = path.read_bytes()
    has_bom = raw[:3] == b"\xef\xbb\xbf"
    text = raw.decode("utf-8-sig")
    uses_crlf = "\r\n" in text
    if uses_crlf:
        text = text.replace("\r\n", "\n")

    m = FM_RE.match(text)
    if not m:
        return {"path": rel_path, "status": "no-frontmatter"}

    open_marker, fm, close_marker, rest = m.groups()

    title_match = TITLE_LINE_RE.search(fm)
    if not title_match:
        return {"path": rel_path, "status": "no-title"}

    current_title = title_match.group(1).strip()
    if not current_title.lower().startswith(PREFIX):
        return {"path": rel_path, "status": "not-relationssearchlistprovider"}

    desired_title, desired_sidebar_title = derive_names(current_title)
    if desired_title is None:
        return {"path": rel_path, "status": "prefix-matches-but-remainder-unrecognized", "title": current_title}

    needs_title_fix = current_title != desired_title
    needs_sidebar_title = not SIDEBAR_TITLE_RE.search(fm)

    if not needs_title_fix and not needs_sidebar_title:
        return {"path": rel_path, "status": "already-correct"}

    new_fm = fm
    if needs_title_fix:
        new_title_line = f"title: {desired_title}"
        new_fm = new_fm[: title_match.start()] + new_title_line + new_fm[title_match.end() :]
    if needs_sidebar_title:
        # Re-locate the title line in new_fm (its span may have shifted if
        # the line above was just rewritten to a different length).
        relocated = TITLE_LINE_RE.search(new_fm)
        new_fm = new_fm[: relocated.end()] + f'\nsidebarTitle: "{desired_sidebar_title}"' + new_fm[relocated.end() :]

    if apply_changes:
        new_text = open_marker + new_fm + close_marker + rest
        if uses_crlf:
            new_text = new_text.replace("\n", "\r\n")
        encoding = "utf-8-sig" if has_bom else "utf-8"
        path.write_bytes(new_text.encode(encoding))

    return {
        "path": rel_path,
        "status": "fixed",
        "title_fixed": needs_title_fix,
        "sidebar_title_added": needs_sidebar_title,
        "title": desired_title,
        "sidebar_title": desired_sidebar_title,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("files", nargs="*", help="Specific files to check (e.g. a PR's changed-files list)")
    parser.add_argument("--path", default=DEFAULT_PATH, help=f"Scope to one folder instead of an explicit file list (default: {DEFAULT_PATH})")
    parser.add_argument("--apply", action="store_true", help="Write the fixes (default: audit only, no writes)")
    args = parser.parse_args()

    candidates = args.files if args.files else list_path_files(args.path)

    results = {
        "fixed": [],
        "already-correct": [],
        "not-relationssearchlistprovider": [],
        "prefix-matches-but-remainder-unrecognized": [],
        "no-frontmatter": [],
        "no-title": [],
    }
    for rel_path in candidates:
        result = process_file(rel_path, args.apply)
        if result is None:
            continue
        results[result["status"]].append(result)

    mode = "Fixed" if args.apply else "Would fix (audit only)"
    print(f"{mode} {len(results['fixed'])} file(s).")
    for r in results["fixed"]:
        parts = []
        if r["title_fixed"]:
            parts.append(f'title: "{r["title"]}"')
        if r["sidebar_title_added"]:
            parts.append(f'sidebarTitle: "{r["sidebar_title"]}"')
        print(f"  {r['path']}: {', '.join(parts)}")

    if results["prefix-matches-but-remainder-unrecognized"]:
        print(f"\nSkipped {len(results['prefix-matches-but-remainder-unrecognized'])} file(s) - has the '{PREFIX}' prefix but the remainder doesn't fully match the known entity/active/passive vocabulary:")
        for r in results["prefix-matches-but-remainder-unrecognized"]:
            print(f"  {r['path']}: title: {r['title']}")

    if results["already-correct"]:
        print(f"\n{len(results['already-correct'])} file(s) already have both fields correct (no-op).")

    print(f"\n{len(results['not-relationssearchlistprovider'])} file(s) don't start with '{PREFIX}' - out of scope, not touched.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
