#!/usr/bin/env python3
"""Warn (never fail) when an internal link's target still carries a literal
`.md`/`.mdx` extension (see issue #421).

Mintlify serves pages at their extension-stripped path -- a source file at
`en/email/inbox/it/index.mdx` serves at `/en/email/inbox/it/index`, never at
`.../index.mdx`. A link authored with the extension still attached is
broken in production even though it looks correct in the raw markdown, and
`contribute/markdown-guide/links-in-docs.mdx` already documents "omit the
file extension" for both markdown links and HTML hrefs.

#421 found 19 such links (HTML `<a href="...">` anchors on `index.mdx`
landing pages, all with a `#fragment` anchor after the extension, e.g.
`.../index.md#how-to-enable-mailkit`) that neither existing checker catches:
tools/triage-broken-links.py resolves a target by checking whether
`<base>.md`/`<base>.mdx`/`<base>/index.md(x)` exists as a tracked file --
since the literal `index.md` source file genuinely exists on disk, it
resolves successfully and the link is never flagged, even though the
*live* URL for that resolved file omits the extension entirely.
tools/ci/check-index-relative-links.py guards a different bug class
(relative `./`/`../` links on index pages, #375/#377/#378) and doesn't
touch extension handling at all.

What is flagged:
  - A markdown link target, or reference-style link definition, or raw
    HTML/JSX href, whose path component ends in `.md` or `.mdx` before an
    optional `#fragment`, `?query`, or the closing delimiter.

What is deliberately NOT flagged:
  - External URLs (`http://`, `https://`) -- e.g. a link into a standards
    document that coincidentally ends in `.md` before its own fragment
    (see the ISO 3166 table link in
    en/api/plugins/quote-connectors/api/data-carriers/addressinfo.md,
    which is not part of this bug class).
  - MDX `import` statements, fenced code blocks, inline code spans, and the
    YAML frontmatter block -- same exclusions as check-index-relative-links.py,
    for the same reasons (sample text or non-navigational, not real links).
  - Files under one of the machine-generated reference trees (see
    GENERATED_TREE_PREFIXES) -- generated by an external pipeline, exempted
    from this bug class the same way #377/#421 exempted them.

This is advisory only -- it never fails the build. It emits a GitHub
Actions warning annotation per hit so it shows up on the PR's Files Changed
tab without blocking anything.

Usage:
    python tools/ci/check-md-extension-links.py <file> [<file> ...]
    python tools/ci/check-md-extension-links.py --path en
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent

# Kept in sync by hand with tools/ci/check-index-relative-links.py's own
# GENERATED_TREE_PREFIXES -- each guard script in this family is
# self-contained (no shared module today), so the constant is duplicated
# rather than imported.
GENERATED_TREE_PREFIXES = (
    "en/api/reference/webapi/",
    "en/api/reference/restful/",
    "en/api/archive-providers/reference/",
    "en/api/mdo-providers/reference/",
    "en/automation/crmscript/reference/",
    "en/automation/trigger/reference/",
    "en/database/tables/",
)

FENCE_LINE_RE = re.compile(r"^[ \t]{0,3}(`{3,}|~{3,})")
INLINE_CODE_SPAN_RE = re.compile(r"`[^`\n]+`")
FRONTMATTER_RE = re.compile(r"\A---\r?\n.*?\r?\n---\r?\n", re.DOTALL)
IMPORT_LINE_RE = re.compile(r"^\s*import\s+.+\s+from\s+['\"].+['\"]\s*;?\s*$")

MD_INLINE_LINK_RE = re.compile(r"\]\(\s*<?([^)\s>]+)>?(?:\s+\"[^\"]*\")?\s*\)")
MD_REF_DEF_RE = re.compile(r'^[ ]{0,3}\[([^\]]+)\]:\s*<?([^\s>]+)>?', re.MULTILINE)
HTML_HREF_RE = re.compile(r'href\s*=\s*[\'"]([^\'"]+)[\'"]', re.IGNORECASE)

EXTERNAL_TARGET_RE = re.compile(r"^[a-z][a-z0-9+.\-]*://", re.IGNORECASE)
# A path segment ending in .md/.mdx, optionally followed by a #fragment or
# ?query, before the link delimiter closes.
MD_EXTENSION_TARGET_RE = re.compile(r"\.mdx?(?:[#?]|$)", re.IGNORECASE)


def mask_fenced_code(text):
    """Blank out fenced code-block bodies, keeping line count and length
    identical so reported line numbers stay accurate. See the identical
    helper in tools/ci/check-index-relative-links.py for the self-closed-fence
    edge case this handles (and why it must not double-toggle in_fence).
    """
    lines = text.split("\n")
    in_fence = False
    for i, line in enumerate(lines):
        m = FENCE_LINE_RE.match(line)
        if m:
            fence_char = m.group(1)[0]
            rest = line[m.end():]
            self_closed = re.search(re.escape(fence_char) + "{3,}", rest)
            lines[i] = ""
            if not self_closed:
                in_fence = not in_fence
            continue
        if in_fence:
            lines[i] = ""
    return "\n".join(lines)


def mask_inline_code_spans(text):
    """Blank out inline code spans (`...`), preserving length/line count."""
    return INLINE_CODE_SPAN_RE.sub(lambda m: " " * len(m.group(0)), text)


def strip_frontmatter(text):
    """Blank out the YAML frontmatter block, preserving line count."""
    m = FRONTMATTER_RE.match(text)
    if not m:
        return text
    blanked = "\n" * m.group(0).count("\n")
    return blanked + text[m.end():]


def strip_import_lines(text):
    """Blank out MDX `import ... from '...'` lines, preserving line count."""
    lines = text.split("\n")
    for i, line in enumerate(lines):
        if IMPORT_LINE_RE.match(line):
            lines[i] = ""
    return "\n".join(lines)


def line_of(text, index):
    return text.count("\n", 0, index) + 1


def is_generated_tree(rel_path):
    return rel_path.startswith(GENERATED_TREE_PREFIXES)


def has_md_extension(target):
    if EXTERNAL_TARGET_RE.match(target):
        return False
    return bool(MD_EXTENSION_TARGET_RE.search(target))


def list_path_files(scope):
    out = subprocess.run(
        ["git", "ls-files", "--", "*.md", "*.mdx"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    files = out.stdout.splitlines()
    scope_norm = scope.strip("/\\").replace("\\", "/")
    return [f for f in files if f == scope_norm or f.startswith(scope_norm + "/")]


def resolve_safe_path(rel_path):
    """Resolve rel_path against REPO_ROOT and refuse anything that escapes
    it (defends against a crafted PR-diff filename attempting path
    traversal -- the changed-files list arrives as untrusted content)."""
    candidate = (REPO_ROOT / rel_path).resolve()
    try:
        candidate.relative_to(REPO_ROOT)
    except ValueError:
        return None
    return candidate


def check_file(rel_path):
    rel_path = rel_path.replace("\\", "/")
    if is_generated_tree(rel_path):
        return []

    path = resolve_safe_path(rel_path)
    if path is None or not path.is_file():
        return []

    text = path.read_bytes().decode("utf-8-sig", errors="replace")
    text = strip_frontmatter(text)
    text = mask_fenced_code(text)
    text = mask_inline_code_spans(text)
    text = strip_import_lines(text)

    hits = []

    for m in MD_INLINE_LINK_RE.finditer(text):
        target = m.group(1)
        if has_md_extension(target):
            hits.append((line_of(text, m.start()), target, "markdown link"))

    for m in MD_REF_DEF_RE.finditer(text):
        target = m.group(2)
        if has_md_extension(target):
            hits.append((line_of(text, m.start()), target, "reference-style link definition"))

    for m in HTML_HREF_RE.finditer(text):
        target = m.group(1)
        if has_md_extension(target):
            hits.append((line_of(text, m.start()), target, "HTML/JSX href"))

    hits.sort(key=lambda h: h[0])
    return hits


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("files", nargs="*", help="Specific files to check (e.g. a PR's changed-files list)")
    parser.add_argument("--path", help="Scope to one folder (e.g. en, release-notes) instead of an explicit file list")
    args = parser.parse_args()

    candidates = list_path_files(args.path) if args.path else args.files

    total_hits = 0
    for rel_path in candidates:
        for line_no, target, kind in check_file(rel_path):
            total_hits += 1
            print(
                f"::warning file={rel_path},line={line_no}::"
                f"Internal {kind} target '{target}' still carries a .md/.mdx "
                f"extension -- Mintlify serves pages with the extension stripped, "
                f"so this link is broken in production (see #421 and "
                f"contribute/markdown-guide/links-in-docs.mdx)."
            )

    if total_hits:
        print(f"\n{total_hits} internal link(s) with a .md/.mdx extension found -- see warnings above.")
    else:
        print("No internal links with a .md/.mdx extension found in the checked files.")

    # Advisory only -- never fail the build.
    return 0


if __name__ == "__main__":
    sys.exit(main())
