#!/usr/bin/env python3
"""
Finds generated reference pages that have fallen out of their tree's nav
file - the fix for #216.

Some content trees are generated by a pipeline that lives outside this repo
(currently: archive-providers, mdo-providers, database/tables - see #192).
Each has a `config/nav-<tree>.json` that gets rewritten whenever the pipeline
pushes new or changed pages. When a source item on the pipeline side is
deleted or renamed, that push removes the entry from the nav file, but
nothing removes the now-unreferenced page from this repo - it keeps existing
as a live, unlinked page (still indexed by site search) with no way to reach
it from the site's own navigation.

This is the same shape of problem #189/#229 solved for api-sources/crmscript,
but simpler: crmscript's generator lives in this repo, so that fix could
regenerate-and-diff to catch drift in both directions. These three trees have
no source file in this repo at all - the only available signal is "file
exists on disk vs. file is referenced in the tree's own nav file," so this
only ever needs to check one direction.

Only files whose frontmatter has `generated: true` are ever reported as
delete candidates - the same signal #164/#165 already use to distinguish
this content from hand-authored pages that happen to live alongside it
(e.g. `en/database/tables/index-by-id.mdx` is linked from `index.mdx` but
was missing from nav - a real nav gap, not stale content; fixed directly in
config/nav-database-tables.json rather than ever being a delete candidate).
Anything stale-looking but not marked `generated: true` is reported
separately, for manual review, and never deleted.

To add a new tree once its pipeline exists (e.g. WebAPI/OpenAPI), add one
entry to TREES below - nothing else in this script is tree-specific.

Usage:
    python tools/find-stale-generated-pages.py [--repo-root <dir>] [--delete]

Exit code is non-zero if any confirmed-generated stale file is found.
"""

import argparse
import json
import os
import re
import sys

TREES = [
    {"folder": "en/api/archive-providers/reference", "nav": "config/nav-archive-providers.json"},
    {"folder": "en/api/mdo-providers/reference", "nav": "config/nav-mdo-providers.json"},
    {"folder": "en/database/tables", "nav": "config/nav-database-tables.json"},
]

PAGE_EXTENSIONS = (".md", ".mdx")
SKIP_DIRS = {"includes"}  # MDX-imported snippet fragments, not standalone pages
GENERATED_RE = re.compile(r"^generated:\s*true\s*$", re.MULTILINE)


def find_page_strings(node, out):
    if isinstance(node, str):
        out.append(node)
    elif isinstance(node, dict):
        if "pages" in node:
            for p in node["pages"]:
                find_page_strings(p, out)
        else:
            for v in node.values():
                find_page_strings(v, out)
    elif isinstance(node, list):
        for item in node:
            find_page_strings(item, out)


def collect_files(folder, repo_root):
    files = {}
    for root, dirs, fnames in os.walk(folder):
        for d in list(dirs):
            if d in SKIP_DIRS:
                dirs.remove(d)
        for fname in fnames:
            for ext in PAGE_EXTENSIONS:
                if fname.endswith(ext):
                    full = os.path.join(root, fname)
                    rel = os.path.relpath(full, repo_root).replace("\\", "/")
                    key = rel[: -len(ext)]
                    files[key] = full
                    break
    return files


def is_generated(path):
    with open(path, "rb") as f:
        raw = f.read()
    text = raw.decode("utf-8-sig", errors="replace")
    if not text.startswith("---"):
        return False
    end = text.find("\n---", 3)
    frontmatter = text[:end] if end != -1 else text
    return bool(GENERATED_RE.search(frontmatter))


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--repo-root", default=".", help="Repo root (default: current directory)")
    parser.add_argument("--delete", action="store_true", help="Delete confirmed-generated stale files instead of only reporting them")
    args = parser.parse_args()

    stale_generated = []
    stale_unmarked = []

    for tree in TREES:
        folder = os.path.join(args.repo_root, tree["folder"])
        nav_path = os.path.join(args.repo_root, tree["nav"])

        files = collect_files(folder, args.repo_root)

        nav_pages = []
        with open(nav_path, encoding="utf-8-sig") as f:
            find_page_strings(json.load(f), nav_pages)
        nav_set = set(nav_pages)

        for key, path in sorted(files.items()):
            if key in nav_set:
                continue
            if is_generated(path):
                stale_generated.append((key, path))
            else:
                stale_unmarked.append((key, path))

    if stale_unmarked:
        print(f"NOT MARKED `generated: true` ({len(stale_unmarked)}) - not in nav, but not touched; needs manual review:")
        for key, _ in stale_unmarked:
            print(f"  {key}")
        print()

    if not stale_generated:
        print("No stale generated pages found.")
        return 0

    print(f"STALE GENERATED PAGES ({len(stale_generated)}) - on disk, but not referenced by their tree's nav file:")
    for key, _ in stale_generated:
        print(f"  {key}")

    if args.delete:
        print()
        print("Deleting...")
        for key, path in stale_generated:
            os.remove(path)
            print(f"  removed {key}")
        return 0

    print()
    print("Re-run with --delete to remove them, or add them back to the relevant nav-*.json if they were actually the target of a nav omission (not a real deletion/rename).")
    return 1


if __name__ == "__main__":
    sys.exit(main())
