#!/usr/bin/env python3
r"""Resolve or fall back every dead DocFX `<see cref="...">` XML-doc
cross-reference in the generated `archive-providers`/`mdo-providers`/`webapi`
reference trees (see #407).

`<see cref="T:Namespace.Type">Label</see>` (and its self-closing form,
`<see cref="T:Namespace.Type" />`) is .NET XML-doc-comment syntax, not HTML.
DocFX used to resolve it into a real hyperlink; Mintlify's MDX renderer does
not -- it either breaks the parser outright (the rare #403 case, already
fixed) or, far more often, silently compiles as an unrecognized custom
element and drops the link, leaving only the bare type name visible. The
HTML-escaped form (`&lt;see cref="..."/&gt;`) is a second, separate failure
mode #407's own filed count missed entirely (same undercounting shape as
#404's raw-vs-escaped split): it isn't dropped, it's rendered as literal,
garbled entity text -- arguably worse for a reader, since #406 already
established that escaping-without-resolving just swaps one bad outcome for
another.

This tree is regenerated by an external ADO pipeline from the same XML doc
comments every time source changes, so a one-time patch would only last
until the next content drop reintroduces the raw markup -- the same shape
already solved for this tree by `fix-webapi-bare-relative-links.py` (#400)
and `fix-reserved-version-property.py` (#291). This script is the permanent,
idempotent fixer; `.github/workflows/generated-reference-autofix.yml` runs
it with --apply on every relevant PR.

Two passes:

1. Build a type -> page lookup:
   - Every archive-providers/mdo-providers reference page opens with a
     self-declaration sentence ("This provider/list name is implemented by
     the class <see cref="T:{FQN}">...</see> inside NetServer's..."), which
     gives a reliable FQN -> "./{own slug}" mapping (one entry per file).
   - Any FQN not covered by that maps its short type name (the last
     dot-segment) against `en/api/reference/webapi/*.md` filenames; an
     exactly-one match resolves to that page's root-relative path. Zero or
     multiple matches are left unresolved rather than guessed at.

2. Rewrite every occurrence (raw or HTML-escaped, paired or self-closing):
   - Display text is the tag's own inner label if present, else the
     resolved-or-not FQN's short type name.
   - Inside frontmatter (a YAML string, never rendered as MDX) -> always
     plain display text, never a markdown link.
   - Otherwise, if the cref's FQN (after normalizing away the DocFX kind
     prefix -- `T:`/`F:`/`M:`/`P:`/`!:`, or the malformed `T -Name` typo
     variant found in 24 occurrences, or no prefix at all) resolves via
     pass 1, AND the resolved target isn't the file's own page (no
     self-links) -> `[display text](target)`.
   - Everything else -> plain display text.

Fenced code blocks and inline code spans are masked before matching (same
`mask_fenced_code`/`mask_inline_code_spans` helpers as
`tools/ci/check-no-new-docfx-see-cref.py`), so a real code example quoting
this syntax (confirmed to exist once, outside this script's three trees) is
never rewritten.

Usage:
    python tools/ci/fix-docfx-see-cref.py                # audit, all 3 trees
    python tools/ci/fix-docfx-see-cref.py --apply         # apply, all 3 trees
    python tools/ci/fix-docfx-see-cref.py --apply <file> ...
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent

DEFAULT_SCOPES = [
    "en/api/archive-providers/reference",
    "en/api/mdo-providers/reference",
    "en/api/reference/webapi",
]

FENCE_LINE_RE = re.compile(r"^[ \t]{0,3}(`{3,}|~{3,})")
INLINE_CODE_SPAN_RE = re.compile(r"`[^`\n]+`")

# Matches a raw or HTML-escaped <see cref="..."> tag, paired or self-closing.
# Group 1/2 = raw form's cref value / inner label; group 3/4 = the same for
# the escaped form.
TAG_RE = re.compile(
    r'<see cref="([^"]*)"(?:\s*/>|>([^<]*)</see>)'
    r'|&lt;see cref="([^"]*)"(?:\s*/&gt;|&gt;([^<]*)&lt;/see&gt;)'
)

# The self-declaration sentence every archive-providers/mdo-providers page
# opens with -- "This provider/list name is implemented by the class
# <see cref="T:{FQN}">...". Also matches the already-fixed plain-text form
# (no <see cref> tag) this same script produces, since the sentence is a
# self-link and always falls back to plain text -- without this, re-running
# the fixer against a tree that's mostly already fixed (the normal case:
# the ADO pipeline regenerates one file, not all 796) would only find a
# self-declaration entry for whichever files still carry the raw tag,
# losing the lookup for every already-fixed page and breaking cross-page
# resolution for the regenerated file's own "See also" references.
SELF_DECL_RE = re.compile(
    r'implemented by the class (?:<see cref="T:([^"]*)">|([A-Za-z0-9_.]+)\b)'
)

# A recognized DocFX kind prefix (T:/F:/M:/P:/!:), or the malformed
# space-dash typo variant (T -Name, no colon at all) found in 24 occurrences.
PREFIX_RE = re.compile(r'^([A-Za-z!]):(.*)$|^([A-Za-z!])\s*-(.*)$')


def mask_fenced_code(text):
    """Blank out fenced code-block bodies, keeping line count and length
    identical. Same approach as tools/ci/check-no-new-docfx-see-cref.py."""
    lines = text.split("\n")
    in_fence = False
    for i, line in enumerate(lines):
        m = FENCE_LINE_RE.match(line)
        if m:
            fence_char = m.group(1)[0]
            rest = line[m.end():]
            self_closed = re.search(re.escape(fence_char) + "{3,}", rest)
            lines[i] = ""
            if not self_closed:
                in_fence = not in_fence
            continue
        if in_fence:
            lines[i] = ""
    return "\n".join(lines)


def mask_inline_code_spans(text):
    return INLINE_CODE_SPAN_RE.sub(lambda m: " " * len(m.group(0)), text)


def normalize_fqn(raw_cref):
    """Strip a recognized DocFX kind prefix (or the malformed T -Name typo)
    from a raw cref value, returning the bare FQN candidate for lookup.
    A cref with no prefix at all (a handful of hand-written cases) is
    passed through as-is -- it's still a plausible type name worth trying."""
    m = PREFIX_RE.match(raw_cref)
    if m:
        rest = m.group(2) if m.group(2) is not None else m.group(4)
        return rest.strip()
    return raw_cref.strip()


def list_scope_files(scope):
    out = subprocess.run(
        ["git", "ls-files", "--", f"{scope}/*.md", f"{scope}/*.mdx"],
        cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    )
    return [f for f in out.stdout.splitlines() if f]


def frontmatter_end_index(lines):
    """Returns the 0-based index of the closing '---' if the file opens
    with a frontmatter block, else -1 (no frontmatter)."""
    if not lines or lines[0].strip() != "---":
        return -1
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            return i
    return -1


def build_lookup(candidates):
    """Pass 1: FQN -> relative link target."""
    self_decl = {}
    for rel_path in candidates:
        if "reference/webapi" in rel_path:
            continue
        text = (REPO_ROOT / rel_path).read_text(encoding="utf-8-sig")
        m = SELF_DECL_RE.search(text)
        if m:
            fqn = m.group(1) if m.group(1) is not None else m.group(2)
            stem = Path(rel_path).stem
            self_decl[fqn] = f"./{stem}"

    webapi_short = {}
    for rel_path in candidates:
        if "reference/webapi" not in rel_path:
            continue
        stem = Path(rel_path).stem
        short = stem.split(".")[-1]
        webapi_short.setdefault(short, []).append(stem)

    return self_decl, webapi_short


def resolve(fqn, self_decl, webapi_short):
    if fqn in self_decl:
        return self_decl[fqn]
    short = fqn.split(".")[-1]
    matches = webapi_short.get(short)
    if matches and len(matches) == 1:
        return f"/en/api/reference/webapi/{matches[0]}"
    return None


def own_targets(rel_path):
    """Every link-target spelling that would point back at rel_path itself,
    so a resolved match equal to the file being edited falls back to plain
    text instead of a self-link."""
    stem = Path(rel_path).stem
    targets = {f"./{stem}"}
    if "reference/webapi" in rel_path:
        targets.add(f"/en/api/reference/webapi/{stem}")
    return targets


def process_file(rel_path, self_decl, webapi_short, apply_changes):
    path = REPO_ROOT / rel_path
    raw = path.read_bytes()
    has_bom = raw[:3] == b"\xef\xbb\xbf"
    uses_crlf = b"\r\n" in raw
    text = raw.decode("utf-8-sig")
    if uses_crlf:
        text = text.replace("\r\n", "\n")

    lines = text.split("\n")
    fm_end = frontmatter_end_index(lines)
    self_link_targets = own_targets(rel_path)

    masked = mask_inline_code_spans(mask_fenced_code(text)).split("\n")

    resolved_count = 0
    fallback_count = 0
    changed = False
    new_lines = []
    for i, (original, masked_line) in enumerate(zip(lines, masked)):
        if "see cref" not in masked_line.lower():
            new_lines.append(original)
            continue

        in_frontmatter = fm_end != -1 and i <= fm_end

        def repl(m):
            nonlocal resolved_count, fallback_count
            raw_cref = m.group(1) if m.group(1) is not None else m.group(3)
            label = m.group(2) if m.group(1) is not None else m.group(4)
            fqn = normalize_fqn(raw_cref)
            display = label.strip() if label else fqn.split(".")[-1]

            if in_frontmatter:
                fallback_count += 1
                return display

            target = resolve(fqn, self_decl, webapi_short)
            if target and target not in self_link_targets:
                resolved_count += 1
                return f"[{display}]({target})"
            fallback_count += 1
            return display

        rewritten = TAG_RE.sub(repl, original)
        if rewritten != original:
            changed = True
        new_lines.append(rewritten)

    if not changed:
        return None, 0, 0

    if apply_changes:
        new_text = "\n".join(new_lines)
        if uses_crlf:
            new_text = new_text.replace("\n", "\r\n")
        encoding = "utf-8-sig" if has_bom else "utf-8"
        path.write_bytes(new_text.encode(encoding))

    return rel_path, resolved_count, fallback_count


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("files", nargs="*", help="Specific files to check (default: all 3 generated-reference trees)")
    parser.add_argument("--apply", action="store_true", help="Rewrite occurrences (default: audit only, no writes)")
    args = parser.parse_args()

    if args.files:
        candidates = args.files
    else:
        candidates = []
        for scope in DEFAULT_SCOPES:
            candidates.extend(list_scope_files(scope))

    self_decl, webapi_short = build_lookup(candidates)
    print(f"Lookup built: {len(self_decl)} self-declaration entries, "
          f"{sum(1 for v in webapi_short.values() if len(v) == 1)} unique WebAPI short-name entries.")

    fixed = []
    total_resolved = 0
    total_fallback = 0
    for rel_path in candidates:
        result, resolved, fallback = process_file(rel_path, self_decl, webapi_short, args.apply)
        total_resolved += resolved
        total_fallback += fallback
        if result is not None:
            fixed.append(result)

    mode = "Rewrote" if args.apply else "Would rewrite (audit only)"
    print(f"{mode} <see cref> occurrences in {len(fixed)} file(s): "
          f"{total_resolved} resolved to a real link, {total_fallback} fell back to plain text.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
