#!/usr/bin/env python3
r"""Resolve every dead DocFX `<xref href="...">`/`<xref:...>` cross-reference
in the generated `archive-providers`/`mdo-providers`/`webapi` reference trees
(see #312/#404), the sibling problem to `fix-docfx-see-cref.py` (#407).

DocFX's `xref` syntax (colon form `<xref:some.uid>`, or tag form
`<xref href="some.uid" data-throw-if-not-resolved="false"></xref>`, both
optionally carrying a `?text=Display+Text` query string) used to resolve into
a real hyperlink; Mintlify's MDX renderer does not. #312/PR #313 did a
repo-wide sweep converting ~90 occurrences to real Mintlify links; #404 found
that the ADO pipeline's own generator re-emits the *same* raw markup every
time it regenerates a page from the underlying XML doc comments, since the
fix only ever lived in this repo's Markdown output, never upstream. Confirmed
again 2026-09-22 (PR #518, the 12.4 content drop): every single occurrence
flagged by `check-no-new-docfx-xref.py` in that PR already had an established,
already-merged resolution on `main` for the exact same sentence.

Unlike `<see cref>` (type-level only), `xref` here also covers member-level
references (a property, field, or method on a WebApi entity/agent class) --
resolved to `path#anchor`, where `anchor` is the generated reference page's
own DocFX-style heading id (dots -> underscores; a method's parameter types
appended the same way, each followed by a trailing underscore -- confirmed by
inspecting real generated anchors, e.g.
`SuperOffice_WebApi_Data_CultureDataFormatter_EncodeDate_System_DateTime_`
for `CultureDataFormatter.EncodeDate(System.DateTime)`). A handful of
`System.*`/`Microsoft.*` framework references resolve to
`learn.microsoft.com` instead (lowercase dotted path; a backtick-arity
generic such as `` System.Tuple`2 `` becomes `system.tuple-2`), matching the
established convention already used throughout this tree for base-class/
built-in-type links.

This tree is regenerated by an external ADO pipeline every time source
changes, so a one-time patch would only last until the next content drop
reintroduces the raw markup -- same shape already solved for this tree by
`fix-webapi-bare-relative-links.py` (#400) and `fix-docfx-see-cref.py` (#407).
This script is the permanent, idempotent fixer.

Usage:
    python tools/ci/fix-docfx-xref.py                # audit, all 3 trees
    python tools/ci/fix-docfx-xref.py --apply         # apply, all 3 trees
    python tools/ci/fix-docfx-xref.py --apply <file> ...
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path
from urllib.parse import unquote, parse_qs

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.markdown_masking import mask_fenced_code, mask_inline_code_spans  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent.parent

DEFAULT_SCOPES = [
    "en/api/archive-providers/reference",
    "en/api/mdo-providers/reference",
    "en/api/reference/webapi",
]

# Raw tag form, its HTML-escaped twin, and the colon form.
TAG_RE = re.compile(
    r'(?:<|&lt;)xref href="([^"]*)"[^>]*>(?:</xref>|&lt;/xref&gt;)'
    r'|(?:<|&lt;)xref:([^>&]+)(?:>|&gt;)'
)

# A small number of DocFX topic uids (colon form) that don't name a .NET type
# at all -- they're hand-authored topic ids from the old DocFx site. No
# general algorithm resolves these; each one is confirmed against `main`'s
# own already-merged fix for the exact same sentence.
COLON_UID_MAP = {
    "rest_api_search_dynamic": ("the dynamic provider reference", "/en/api/search/odata/dynamic-provider"),
}

FRAMEWORK_PREFIXES = ("System.", "Microsoft.")


def list_scope_files(scope):
    out = subprocess.run(
        ["git", "ls-files", "--", f"{scope}/*.md", f"{scope}/*.mdx"],
        cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    )
    return [f for f in out.stdout.splitlines() if f]


def build_lookup(candidates):
    """webapi tree only: short type name -> [full FQN stems], plus the full
    set of stems for exact-match lookups. Same shape as
    fix-docfx-see-cref.py's `webapi_short`, since xref member-level refs only
    ever target the webapi tree in practice."""
    stems = set()
    short = {}
    for rel_path in candidates:
        if "reference/webapi" not in rel_path:
            continue
        stem = Path(rel_path).stem
        stems.add(stem)
        short.setdefault(stem.split(".")[-1], []).append(stem)
    return stems, short


def strip_params(fqn):
    """Split a trailing `(Param1,Param2)` method signature off an FQN.
    Returns (base, params_or_None)."""
    m = re.match(r'^(.*)\(([^()]*)\)$', fqn)
    if not m:
        return fqn, None
    base = m.group(1)
    inner = m.group(2).strip()
    params = [p.strip() for p in inner.split(",") if p.strip()] if inner else []
    return base, params


def ms_learn_target(fqn_base, member):
    """Resolve a System.*/Microsoft.* reference to a learn.microsoft.com URL.
    `member` is None for a bare type reference."""
    full = fqn_base if member is None else f"{fqn_base}.{member}"
    lowered = full.lower().replace("`", "-")
    return f"https://learn.microsoft.com/dotnet/api/{lowered}"


def resolve(fqn_base, params, stems, short):
    """Resolve a SuperOffice.* xref target (params off already). Returns
    (target_path, anchor_or_None) or (None, None) if unresolved."""
    if fqn_base in stems:
        return f"/en/api/reference/webapi/{fqn_base}", None

    top_short = fqn_base.split(".")[-1]
    if params is None:
        matches = short.get(top_short)
        if matches and len(matches) == 1:
            return f"/en/api/reference/webapi/{matches[0]}", None

    if "." not in fqn_base:
        return None, None

    type_part, member = fqn_base.rsplit(".", 1)

    def anchor_for(stem):
        a = stem.replace(".", "_") + "_" + member
        if params:
            a += "_" + "_".join(p.replace(".", "_") for p in params) + "_"
        return a

    if type_part in stems:
        return f"/en/api/reference/webapi/{type_part}", anchor_for(type_part)

    type_short = type_part.split(".")[-1]
    matches = short.get(type_short)
    if matches and len(matches) == 1:
        stem = matches[0]
        return f"/en/api/reference/webapi/{stem}", anchor_for(stem)

    return None, None


def process_file(rel_path, stems, short, apply_changes):
    path = REPO_ROOT / rel_path
    raw = path.read_bytes()
    has_bom = raw[:3] == b"\xef\xbb\xbf"
    uses_crlf = b"\r\n" in raw
    text = raw.decode("utf-8-sig")
    if uses_crlf:
        text = text.replace("\r\n", "\n")

    lines = text.split("\n")
    masked = mask_inline_code_spans(mask_fenced_code(text)).split("\n")

    resolved_count = 0
    unresolved_count = 0
    changed = False
    new_lines = []
    for original, masked_line in zip(lines, masked):
        if "xref" not in masked_line.lower():
            new_lines.append(original)
            continue

        def repl(m):
            nonlocal resolved_count, unresolved_count
            href, colon_uid = m.group(1), m.group(2)

            if colon_uid is not None:
                uid = unquote(colon_uid.strip())
                mapped = COLON_UID_MAP.get(uid)
                if mapped:
                    resolved_count += 1
                    display, target = mapped
                    return f"[{display}]({target})"
                unresolved_count += 1
                return m.group(0)

            path_part, _, query = href.partition("?")
            fqn_raw = unquote(path_part)
            display = None
            if query:
                q = parse_qs(query)
                if "text" in q and q["text"]:
                    display = q["text"][0]

            fqn_base, params = strip_params(fqn_raw)

            if fqn_base.startswith(FRAMEWORK_PREFIXES):
                if params is not None:
                    # No framework method in this tree currently needs
                    # parameter-aware disambiguation; link to the member's
                    # containing page without an anchor rather than guess.
                    type_part, member = fqn_base.rsplit(".", 1) if "." in fqn_base else (fqn_base, None)
                    target = ms_learn_target(type_part, None)
                else:
                    if "." in fqn_base:
                        type_part, member = fqn_base.rsplit(".", 1)
                    else:
                        type_part, member = fqn_base, None
                    # Prefer the bare type page unless this is clearly a
                    # member (lowercase-first-letter heuristic doesn't
                    # apply here; framework members seen so far are fields
                    # like DateTime.MinValue, so always try type.member first).
                    target = ms_learn_target(fqn_base, None)
                if display is None:
                    display = fqn_raw.split(".")[-1].rstrip("()")
                resolved_count += 1
                return f"[{display}]({target})"

            target, anchor = resolve(fqn_base, params, stems, short)
            if target is None:
                unresolved_count += 1
                return m.group(0)

            resolved_count += 1
            if display is None:
                display = fqn_base.split(".")[-1]
            full_target = f"{target}#{anchor}" if anchor else target
            return f"[{display}]({full_target})"

        rewritten = TAG_RE.sub(repl, original)
        if rewritten != original:
            changed = True
        new_lines.append(rewritten)

    if not changed:
        return None, 0, 0

    if apply_changes:
        new_text = "\n".join(new_lines)
        if uses_crlf:
            new_text = new_text.replace("\n", "\r\n")
        encoding = "utf-8-sig" if has_bom else "utf-8"
        path.write_bytes(new_text.encode(encoding))

    return rel_path, resolved_count, unresolved_count


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("files", nargs="*", help="Specific files to check (default: all 3 generated-reference trees)")
    parser.add_argument("--apply", action="store_true", help="Rewrite occurrences (default: audit only, no writes)")
    args = parser.parse_args()

    if args.files:
        candidates = args.files
    else:
        candidates = []
        for scope in DEFAULT_SCOPES:
            candidates.extend(list_scope_files(scope))

    stems, short = build_lookup(candidates)
    print(f"Lookup built: {len(stems)} WebApi page stems, "
          f"{sum(1 for v in short.values() if len(v) == 1)} unique short-name entries.")

    fixed = []
    total_resolved = 0
    total_unresolved = 0
    for rel_path in candidates:
        result, resolved, unresolved = process_file(rel_path, stems, short, args.apply)
        total_resolved += resolved
        total_unresolved += unresolved
        if result is not None:
            fixed.append(result)

    mode = "Rewrote" if args.apply else "Would rewrite (audit only)"
    print(f"{mode} <xref> occurrences in {len(fixed)} file(s): "
          f"{total_resolved} resolved to a real link, {total_unresolved} left unresolved.")
    if total_unresolved:
        print("Unresolved occurrences were left untouched -- re-run without --apply and inspect manually.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
