#!/usr/bin/env python3
"""Generate the six per-language "userhelp" sitemap pages Userflow's in-app
Resource Center reads (see issue #173).

Userflow's Resource Center has a "Knowledge base URL" setting per language,
pointed at `docs.superoffice.com/learn-<lang>.html` today. That file was
generated by the legacy DocFx pipeline (build-docs.ps1 -> tools/build-learn-
html-files.ps1 -> tools/build-learn-from-files-with-index.ps1, in the old
build-docs checkout) as a flat list of links to every page under a `learn/`
folder, plus any page elsewhere hand-flagged by the Userflow team. This tool
reproduces that page set for the Mintlify content tree.

Selection logic per language <lang> (en, da, de, nl, no, sv):
  - Every page whose path starts with `<lang>/` and contains a `/learn/`
    segment anywhere after that.
  - Every page anywhere in the repo with `userflow-index: true` frontmatter:
      - if its path starts with a recognized language prefix, it belongs to
        that language only (a real per-language page, e.g. an `admin/`
        how-to)
      - if it has no language prefix at all (e.g. `integrations/`,
        `release-notes/` -- content areas that were consolidated out of
        per-language duplicates during the Mintlify migration, or were
        always shared), it belongs to EVERY language's file. Confirmed via
        `integrations/mail-link/index.md`'s `redirect_from` history, which
        shows six separate per-language pages before consolidation.

The resulting page set for each language is cross-checked against that
language's own resolved nav tree (config/nav-<lang>.json, following `$ref`s
the same way Mintlify's docs.json does) -- language-prefixed pages against
their own language's nav, unprefixed/shared pages against the fully-resolved
English nav tree (the only one that individually enumerates
integrations/release-notes content; other languages only have a single
shallow stub page for those tabs). A hand-flagged page missing from the
relevant nav tree is logged, not dropped -- it's still a real page Userflow
should be able to link to, but nav-listing drift is worth a human's
attention.

No dependency on a built site, Mintlify's own `sitemap.xml`, or any other
build artifact -- this walks the checked-in source tree and nav config
directly, so it's safe and correct to re-run any time a `learn/` or
`userflow-index` page is added, moved, renamed, or deleted, independent of
any scheduled regeneration.

Output: `learn-<lang>.mdx` at the repo root, one per language, `hidden: true`
(reachable by direct URL, excluded from the sidebar and from Mintlify's own
`sitemap.xml`/search indexing -- see contribute/markdown-guide/metadata.mdx),
body a flat markdown link list. The old DocFx-era `/learn-<lang>.html` URL
Userflow's dashboard setting still points at is bridged via a `config/
redirects.json` entry, not `redirect_from` frontmatter (which has no
practical build-time effect on its own).

Usage:
    python tools/build-learn-sitemaps.py            # audit, no writes
    python tools/build-learn-sitemaps.py --apply     # write the six pages
"""

import argparse
import json
import re
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_DIR = REPO_ROOT / "config"
CANONICAL_BASE = "https://docs.superoffice.com"
LANGUAGES = ["en", "da", "de", "nl", "no", "sv"]

FM_RE = re.compile(r"^(---\n)(.*?\n)(---\n?)(.*)$", re.DOTALL)
USERFLOW_INDEX_RE = re.compile(r"^userflow-index:\s*true\s*$", re.MULTILINE)


def list_content_files():
    out = subprocess.run(
        ["git", "ls-files", "--", "*.md", "*.mdx"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return [f for f in out.stdout.splitlines() if "/includes/" not in f and not f.startswith("includes/")]


def url_path_for(rel_path):
    """Mintlify uses the bare repo-relative path (no extension) as the URL --
    confirmed via config/nav-*.json, which lists page paths this way,
    including a literal trailing `/index` (not collapsed to a directory
    root)."""
    p = Path(rel_path)
    return str(p.with_suffix("")).replace("\\", "/")


def language_of(rel_path):
    first_segment = rel_path.split("/", 1)[0]
    return first_segment if first_segment in LANGUAGES else None


def has_userflow_index(rel_path):
    path = REPO_ROOT / rel_path
    text = path.read_text(encoding="utf-8-sig")
    m = FM_RE.match(text)
    if not m:
        return False
    _, fm, _, _ = m.groups()
    return bool(USERFLOW_INDEX_RE.search(fm))


def collect_pages_per_language():
    pages = {lang: set() for lang in LANGUAGES}

    for rel_path in list_content_files():
        lang = language_of(rel_path)
        segments = rel_path.split("/")

        if lang and "learn" in segments[1:]:
            pages[lang].add(rel_path)

        if has_userflow_index(rel_path):
            if lang:
                pages[lang].add(rel_path)
            else:
                for other_lang in LANGUAGES:
                    pages[other_lang].add(rel_path)

    return pages


def resolve_nav(node, base_dir):
    if isinstance(node, dict):
        if set(node.keys()) == {"$ref"}:
            ref_path = (base_dir / node["$ref"]).resolve()
            with open(ref_path, encoding="utf-8") as f:
                ref_data = json.load(f)
            return resolve_nav(ref_data, ref_path.parent)
        return {k: resolve_nav(v, base_dir) for k, v in node.items()}
    if isinstance(node, list):
        return [resolve_nav(item, base_dir) for item in node]
    return node


def find_page_strings(node, out):
    if isinstance(node, str):
        out.append(node)
    elif isinstance(node, dict):
        if "pages" in node:
            find_page_strings(node["pages"], out)
        if "groups" in node:
            find_page_strings(node["groups"], out)
        if "root" in node and isinstance(node["root"], str):
            out.append(node["root"])
    elif isinstance(node, list):
        for item in node:
            find_page_strings(item, out)


def nav_page_set(lang):
    nav_path = CONFIG_DIR / f"nav-{lang}.json"
    with open(nav_path, encoding="utf-8") as f:
        raw = json.load(f)
    resolved = resolve_nav(raw, CONFIG_DIR)
    out = []
    find_page_strings(resolved, out)
    return {p.split("#")[0] for p in out}


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--apply", action="store_true", help="Write the six learn-<lang>.mdx files (default: audit only)")
    args = parser.parse_args()

    pages_per_language = collect_pages_per_language()
    en_nav = nav_page_set("en")

    for lang in LANGUAGES:
        pages = sorted(pages_per_language[lang])
        lang_nav = nav_page_set(lang)

        missing_from_nav = []
        for rel_path in pages:
            url = url_path_for(rel_path)
            page_lang = language_of(rel_path)
            nav_set = lang_nav if page_lang == lang else en_nav
            if url not in nav_set:
                missing_from_nav.append(rel_path)

        print(f"{lang}: {len(pages)} page(s) for learn-{lang}.mdx")
        if missing_from_nav:
            print(f"  NOT FOUND in relevant nav tree ({len(missing_from_nav)}) -- still included, flagged for review:")
            for m in missing_from_nav:
                print(f"    {m}")

        if args.apply:
            lines = [
                "---",
                f"uid: userhelp-sitemap-{lang}",
                f"title: Userflow help index ({lang})",
                "description: Generated link list Userflow's Resource Center knowledge-base search reads for this language. Not a page for humans.",
                "hidden: true",
                f"language: {lang}",
                "---",
                "",
            ]
            for rel_path in pages:
                url = f"{CANONICAL_BASE}/{url_path_for(rel_path)}"
                lines.append(f"* [{url}]({url})")
            out_path = REPO_ROOT / f"learn-{lang}.mdx"
            out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
            print(f"  wrote {out_path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
