#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Generates components/custom-mode-footer.mdx from docs.json footer data.

.DESCRIPTION
    Reads footer.links, footer.socials, and logo.href from docs.json and
    writes a JSX-ready MDX component to components/custom-mode-footer.mdx.

    Run this script whenever the [footer] section of docs.json changes:

        .\tools\generate-footer.ps1

    The generated file is committed to git — pages import it without
    needing to run the script at build time.

.NOTES
    Logo paths are hardcoded as /logo/light.svg (LM) and /logo/dark.svg (DM)
    regardless of docs.json logo config, because that config is tuned for
    the SO-green navbar background, not the page body background.

    Social icons are brand SVGs stored in /logo/social-*.svg (2026 brand pack).
    X/Twitter is excluded — not in the brand asset set.
    Icons are self-contained (green circle + dune-white glyph) and work on
    both LM and DM without CSS color adaptation.
#>

$ErrorActionPreference = 'Stop'

$repoRoot   = Split-Path -Parent $PSScriptRoot
$docsFile   = Join-Path $repoRoot 'docs.json'
$outputFile = Join-Path $repoRoot 'components' 'custom-mode-footer.mdx'

# ── validate ─────────────────────────────────────────────────
if (-not (Test-Path $docsFile)) {
    Write-Error "docs.json not found: $docsFile"
    exit 1
}

Write-Host "Processing: $docsFile" -ForegroundColor Cyan

# ── read docs.json ───────────────────────────────────────────
$docs     = Get-Content $docsFile -Raw | ConvertFrom-Json
$footer   = $docs.footer
$logoHref = $docs.logo.href

# ── brand SVG icon filenames (stored in /logo/social-*.svg) ──
# X/Twitter excluded — not in the 2026 brand asset set.
$iconFiles = @{
    youtube   = 'social-youtube.svg'
    facebook  = 'social-facebook.svg'
    instagram = 'social-instagram.svg'
    linkedin  = 'social-linkedin.svg'
}
$labels = @{
    youtube = 'YouTube'; facebook = 'Facebook'
    instagram = 'Instagram'; linkedin = 'LinkedIn'
}

# ── link columns ─────────────────────────────────────────────
$colHtml = foreach ($group in $footer.links) {
    $links = ($group.items | ForEach-Object {
        "        <a href=""$($_.href)"">$($_.label)</a>"
    }) -join "`n"
    "      <div className=""cmf-link-col"">`n$links`n      </div>"
}

# ── social icons ─────────────────────────────────────────────
$socialHtml = foreach ($s in $footer.socials.PSObject.Properties) {
    if ($iconFiles.Contains($s.Name)) {
        $label = $labels[$s.Name]
        $file  = $iconFiles[$s.Name]
        "      <a href=""$($s.Value)"" aria-label=""$label"" className=""cmf-social"">`n        <img src=""/logo/$file"" alt=""$label"" width=""32"" height=""32"" />`n      </a>"
    }
}

# ── assemble ─────────────────────────────────────────────────
$colBlock    = $colHtml    -join "`n"
$socialBlock = $socialHtml -join "`n"

$mdx = @"
{/* DO NOT EDIT — generated by tools/generate-footer.ps1
    Run that script to regenerate whenever docs.json footer data changes.
    Logo paths are intentionally hardcoded (light.svg for LM, dark.svg for DM)
    independent of docs.json logo config, which is tuned for the navbar. */}

<div id="custom-mode-footer">
  <div id="custom-mode-footer-inner">

    <a href="$logoHref" id="custom-mode-footer-brand" aria-label="SuperOffice home">
      <img src="/logo/light.svg" className="cmf-logo-light" alt="SuperOffice" />
      <img src="/logo/dark.svg"  className="cmf-logo-dark"  alt="SuperOffice" />
    </a>

    <div id="custom-mode-footer-links">
$colBlock
    </div>

    <div id="custom-mode-footer-socials">
$socialBlock
    </div>

  </div>
</div>
"@

# ── write ─────────────────────────────────────────────────────
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($outputFile, $mdx, $utf8NoBom)

Write-Host "  $outputFile" -ForegroundColor Yellow
Write-Host "`nComplete!" -ForegroundColor Green
exit 0
